import localFont from "next/font/local";
import { Instrument_Serif, Neuton } from 'next/font/google'
import "./globals.css";


const satoshimed = localFont({
  src: "./fonts/Satoshi-Medium.otf",
  variable: "--font-satoshi-medium",
  weight: "500 ",
});
const neuton = Neuton({
  subsets: ['latin'],
  variable: '--font-neuton',
  weight: ['400', '700'],
  display: 'swap',
})
const instrumentserif = Instrument_Serif({
  subsets: ['latin'],
  variable: '--font-instrument-serif',
  weight: ['400'],
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${satoshimed.variable} ${neuton.variable} ${instrumentserif.variable}  bg-white  `}
      >
        {children}
      </body>
    </html>
  );
}
